#pragma kernel Surround

#include "./Perlin.compute"

static const int numThreads = 16;

StructuredBuffer<int3> positions;
RWStructuredBuffer<int> surroundings;

[numthreads(numThreads, 1, 1)]
void Surround(uint3 id : SV_DispatchThreadID) {
    int mask = 0;
    for (int i = 0; i < 8; i++) {
        float3 pos = float3((i & 1), ((i >> 1) & 1), (i >> 2));
        pos += positions[id.x];
        mask |= ((perlinDot(pos * dotsScale)) << i);
    }

    surroundings[id.x] = mask;
}
